version: '3'

services:
  database:
    image: postgres:11
    environment:
      - "POSTGRES_DB=chat"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./:/var/www